// Regenerates web/src/lib/export/slackAssets.ts from the Slack skin source files
// so the standalone export template can inline them without vite's ?raw loader
// (keeps node-based tests working). Run: node scripts/genSlackAssets.mjs
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const css = readFileSync(join(root, 'web/src/components/simulators/slack.css'), 'utf8')
const js = readFileSync(join(root, 'web/src/lib/export/slackRuntime.js'), 'utf8')
const out = `// AUTO-GENERATED by scripts/genSlackAssets.mjs — do not edit by hand.
// Regenerate after editing slack.css or slackRuntime.js.
/* eslint-disable */
export const SLACK_CSS = ${JSON.stringify(css)}
export const SLACK_RUNTIME = ${JSON.stringify(js)}
`
writeFileSync(join(root, 'web/src/lib/export/slackAssets.ts'), out)
console.log('wrote web/src/lib/export/slackAssets.ts (css %d bytes, js %d bytes)', css.length, js.length)
