// Bundles the standalone Slack entry (React inlined + slack.css) into
// web/src/lib/export/slackStandaloneBundle.ts as JS + CSS strings, so the
// downloadable export renders the exact same React SlackFrame as the preview.
// Run: node scripts/genSlackStandalone.mjs  (also runs on prebuild)
import * as esbuild from 'esbuild'
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

const result = await esbuild.build({
  entryPoints: [join(root, 'web/src/standaloneSlack.tsx')],
  bundle: true,
  minify: true,
  format: 'iife',
  jsx: 'automatic',
  target: ['es2019'],
  define: { 'process.env.NODE_ENV': '"production"' },
  write: false,
  outfile: join(root, 'web/src/lib/export/_slack-standalone.js'),
})

let js = ''
let css = ''
for (const f of result.outputFiles) {
  if (f.path.endsWith('.css')) css = f.text
  else js = f.text
}
if (!js) throw new Error('genSlackStandalone: no JS output produced')

const out = `// AUTO-GENERATED by scripts/genSlackStandalone.mjs — do not edit by hand.
/* eslint-disable */
export const SLACK_STANDALONE_JS = ${JSON.stringify(js)}
export const SLACK_STANDALONE_CSS = ${JSON.stringify(css)}
`
writeFileSync(join(root, 'web/src/lib/export/slackStandaloneBundle.ts'), out)
console.log('wrote slackStandaloneBundle.ts (js %d KB, css %d KB)', Math.round(js.length / 1024), Math.round(css.length / 1024))
